### ISSUE TITLE
(RuntimeError) "multi_response has completed"

### ISSUE THREAD

**Issue by rajofchennai** [petergoldstein/dalli#432]
I got this error once. I saw that this exception was raised 

https://github.com/mperham/dalli/blob/57943358b4701d814d861409cc01dab237290fe6/lib/dalli/server.rb#L140

Just want to know in what case this might happen?

```
/home/ubuntu/.rvm/gems/ruby-2.0.0-p247@spaghetti/ruby/2.0.0/gems/dalli-2.7.0/lib/dalli/server.rb:140:in `multi_response_nonblock'
/home/ubuntu/.rvm/gems/ruby-2.0.0-p247@spaghetti/ruby/2.0.0/gems/dalli-2.7.0/lib/dalli/options.rb:42:in `block in multi_response_nonblock' 
/home/ubuntu/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize' 
/home/ubuntu/.rvm/gems/ruby-2.0.0-p247@spaghetti/ruby/2.0.0/gems/dalli-2.7.0/lib/dalli/options.rb:41:in `multi_response_nonblock'
 /home/ubuntu/.rvm/gems/ruby-2.0.0-p247@spaghetti/ruby/2.0.0/gems/dalli-2.7.0/lib/dalli/client.rb:413:in `block (4 levels) in get_multi_yielder' 
/home/ubuntu/.rvm/gems/ruby-2.0.0-p247@spaghetti/ruby/2.0.0/gems/dalli-2.7.0/lib/dalli/client.rb:409:in `each'
 /home/ubuntu/.rvm/gems/ruby-2.0.0-p247@spaghetti/ruby/2.0.0/gems/dalli-2.7.0/lib/dalli/client.rb:409:in `block (3 levels) in get_multi_yielder' 
/home/ubuntu/.rvm/gems/ruby-2.0.0-p247@spaghetti/ruby/2.0.0/gems/dalli-2.7.0/lib/dalli/client.rb:385:in `loop'
/home/ubuntu/.rvm/gems/ruby-2.0.0-p247@spaghetti/ruby/2.0.0/gems/dalli-2.7.0/lib/dalli/client.rb:385:in `block (2 levels) in get_multi_yielder'
 /home/ubuntu/.rvm/gems/ruby-2.0.0-p247@spaghetti/ruby/2.0.0/gems/dalli-2.7.0/lib/dalli/ring.rb:51:in `lock' 
/home/ubuntu/.rvm/gems/ruby-2.0.0-p247@spaghetti/ruby/2.0.0/gems/dalli-2.7.0/lib/dalli/client.rb:372:in `block in get_multi_yielder' 
/home/ubuntu/.rvm/gems/ruby-2.0.0-p247@spaghetti/ruby/2.0.0/gems/dalli-2.7.0/lib/dalli/client.rb:316:in `call' /home/ubuntu/.rvm/gems/ruby-2.0.0-p247@spaghetti/ruby/2.0.0/gems/dalli-2.7.0/lib/dalli/client.rb:316:in `perform' 

/home/ubuntu/.rvm/gems/ruby-2.0.0-p247@spaghetti/ruby/2.0.0/gems/dalli-2.7.0/lib/dalli/client.rb:370:in `get_multi_yielder'
 /home/ubuntu/.rvm/gems/ruby-2.0.0-p247@spaghetti/ruby/2.0.0/gems/dalli-2.7.0/lib/dalli/client.rb:65:in `block in get_multi' 
/home/ubuntu/.rvm/gems/ruby-2.0.0-p247@spaghetti/ruby/2.0.0/gems/dalli-2.7.0/lib/dalli/client.rb:64:in `tap' 
/home/ubuntu/.rvm/gems/ruby-2.0.0-p247@spaghetti/ruby/2.0.0/gems/dalli-2.7.0/lib/dalli/client.rb:64:in `get_multi'
```

**Comment by petergoldstein** [comment]
Still no idea.  :)  As this was a one-off incident, and there have been no similar reports for over a year, I'm going to close.

@rajofchennai Please feel free to reopen if this is a recurring issue for you.

**Comment by jonhyman** [comment]
@petergoldstein We've been getting this a couple times per day since we started using a remote memcached last Friday. For about 6 months we've had a memcached instance installed on all our servers and used some caching at `127.0.0.1:11211`. Last Friday we replaced our redis caching with a 9-node memcached cluster and have seen this probably two dozen times since then.

**Comment by Will-Sommers** [comment]
Hi @petergoldstein we've also been getting this with a distributed cluster specifically after we flush our cache.

**Comment by petergoldstein** [comment]
@jonhyman @Will-Sommers  It sounds like there's an issue here, but I'm not going to be able to look at it for a couple of weeks.  If you can collect more details in the interim, that would be helpful.  At a minimum it sounds like the problem requires a distributed cluster to manifest.

My initial hypothesis is that the error should be caught in the following block in `Dalli::Client` - https://github.com/petergoldstein/dalli/blob/94ce53c77a8265ec46c6432b0f5c8e9396e2a789/lib/dalli/client.rb#L451-461 and that we can simply change the error line here - https://github.com/petergoldstein/dalli/blob/7cdd200dbfbed2164f49380e5032d8d7e3bc1275/lib/dalli/server.rb#L151 to raise an appropriately a typed exception.  If either of you want to try that out on your own systems and submit a PR, that might accelerate the process.

**Comment by Will-Sommers** [comment]
@petergoldstein I went back and looked and we weren't flushing memcached correctly which raised this exception. Our script was basically a `kill` on the MC process and then a restart. I'll take a stab at it and see what happened.

**Comment by rihadik** [comment]
Hi, we're also seeing this error in a distributed memcached environment w/ Unicorn, about once a day or more. We haven't been able to attribute it to a networking/resource problem.

**Comment by reneklacan** [comment]
We are experiencing this as well when we set a `pool_size` for Dalli (which also sets `thread_safe` to `false`)

**Comment by sweatC** [comment]
Also, have some troubles with this. But it only appears on staging.
@petergoldstein  Any, updates?
![image](https://user-images.githubusercontent.com/15202961/43195936-296dcd3a-900f-11e8-9e7c-2ee7af3d53f6.png)

**Comment by tanasegabriel** [comment]
We experienced this as a result of setting `idle_timeout` on our Memcached servers. This controls the number of seconds a client will be allowed to **idle** before being **asked to close,** the definition of this on Memcached code base can be found [here](https://github.com/memcached/memcached/blob/79f90d1ebfa61786ad7a821e4aa42da589c77ba5/memcached.c#L505-L523). After applying this and restarting our Memcached servers, we saw a high rate of exceptions, in cycles of 450 seconds (the value set of `idle_timeout`, which we considered to be conservative enough to not affect Dalli). As you can see from this graph, we have a pretty low base of exceptions (purple bars), but the yellow bars represent to exceptions thrown while having `idle_timeout` enabled (we set it back to 0 afterwards):

![image](https://user-images.githubusercontent.com/20187768/61522881-2eea9b00-aa0b-11e9-9b30-841a4efb2924.png)

The most commonly seen exceptions are:
- `RuntimeError multi_response has completed`
- `<memcached_endpoint>:11211 failed (count: 0) EOFError: end of file reached` (the result of connections being closed)
- `<memcached_endpoint>:11211 failed (count: 0) RuntimeError: Already writing to socket`
- `undefined method <method_name> for <object>`

The first two exceptions seem to be the result of connections being closed, but we're unsure why Dalli reacted badly to this.

The last two exceptions are a bit more interesting - it looks like we fetched the wrong object from the cache (some form of connection mangling?)

After reverting our change, these exceptions disappeared (including the wrong fetches).

It's worth mentioning that we applied this change to two Memcached clusters, both of them having the same effect on Dalli.

Our Dalli settings:

```
cluster_1: {
    expires_in: 7.days,
    failover: false,
    socket_timeout: 0.5,
    down_retry_delay: 60,
    socket_max_failures: 5,
    compress: true,
    pool_size: 30,
    pool_timeout: 5,
    value_max_bytes: 104857600,
    instrument_errors: true,
    instrument_namespace: <namespace_cluster_1>,
  }
```
```
cluster_2: {
    expires_in: 5.days,
    failover: false,
    socket_timeout: 0.5,
    down_retry_delay: 60,
    socket_max_failures: 5,
    compress: true,
    pool_size: 30,
    pool_timeout: 5,
    value_max_bytes: 104857600,
    instrument_errors: true,
    instrument_namespace: <namespace_cluster_2>,
  }
```
We run AWS hosted Memcached, bot of these clusters running engine version `1.5.10`, while the version of the Dalli client is `2.7.9`


Mentioning @petergoldstein, seeing how this issue is quite old now (hope this is OK).

If we can provide any logs to help debug this issue, we'll be happy to!

**Comment by GregFarrell** [comment]
We (I'm at the same company as @tanasegabriel) have dug into this ourselves.

The problem, when using idle_timeout, seems to be mainly due to the fact that Memcache (prior to 2 months ago) has a bug where it does not reset the idle timeout count when receiving binary protocol commands.

There is a fix for this in v1.5.15.
https://github.com/memcached/memcached/commit/c5a598e19e716c2b26a0ba3552bd68d9e3da0f50

Once AWS rollout this fix, then we will see if this fixes the problem for us. I'll feed back any useful information that we get if it doesn't; for posterity for anyone else experiencing the same problem.

**Comment by jonswar** [comment]
Whenever we stop memcached, we get a lot of these errors, as well as cache value corruption (e.g. "undefined method `[]' for true:TrueClass", meaning memcached returned true for an array value - as in [issue 146](https://github.com/petergoldstein/dalli/issues/146)).

We are not using idle_timeout. Our config is simply

`
    {:expires_in=>1800, :compress=>true, :socket_timeout=>0.05, :pool=>"default"}
`

dalli 2.7.10, memcached server 1.5.12 and 1.5.20 (has happened with both).

@Will-Sommers says "we weren't flushing memcached correctly which raised this exception. Our script was basically a kill on the MC process and then a restart." Are we supposed to flush memcached before killing it?? If so how?

**Comment by jonswar** [comment]
But what does "multi_response has completed" mean??

**Comment by mperham** [comment]
@jonswar I have not looked at Dalli in five years. I'm getting back into the project a bit but declared issue bankruptcy and closed everything as I don't have the time to go thru each. If this problem is still relevant, please open a new issue with the latest data against 2.7.11 and sorry for the trouble.
