### ISSUE TITLE
Hi, I am getting this issu,RuntimeError: Cannot share client between multiple processes 

### ISSUE THREAD

**Issue by heraju** [petergoldstein/dalli#440]
config file:
defaults:
  ttl: 1800
  readonly: false
  urlencode: false
  c_threshold: 10000
  compression: true
  debug: false
  namespace: ""
  sessions: true
  fragments: true
  memory: 128
  servers:
      - my-test-server:11211
  benchmarking: true
  raise_errors: true
  fast_hash: false
  fastest_hash: false

error:
 my-test-server:11211 failed (count: 0) RuntimeError: Cannot share client between multiple processes
# <Dalli::NetworkError: Socket operation failed, retrying...>

retrying request with new server
Dalli::Server#connect my-test-server:11211

I have two nodes of AWS elastic cache server, when multiple users hit the same cache.

Am i missing some configs, please help.
Thanks in advance.

**Comment by driehuis** [comment]
It seems that the error message people are seeing (and I'm seeing it too) is misleading. I'm getting
this error message:
```
localhost:11211 failed (count: 0) RuntimeError: Cannot share client between multiple processes
```
Reading the code, it appears to be the fix for issue #208 in action: it detects the fork, prints this intimidating message, and then proceeds to reconnect. My app appears to work fine, but I never got to check that, because I first wanted to fix this error.

My concern is twofold. First, if the message is just a warning that Dalli is re-opening the socket because it detected a fork(), it should probably be reworded to something like "fork detected, re-connecting to memcached to avoid mixing data streams".

Second, the mechanism counts toward the socket_max_failures counter, which I'm not sure is correct, as one is now one brief hickup away from not connecting at all with the default socket_max_failures.

**Comment by hishammalik** [comment]
agree with @driehuis that the message is misleading.

**Comment by wjordan** [comment]
After stumbling upon this error message myself, I implemented @driehuis's [suggestions](https://github.com/mperham/dalli/issues/440#issuecomment-75461363) in PR #556. @mperham could you comment on whether this seems like a good way to avoid future confusion on this issue?

**Comment by petergoldstein** [comment]
@wjordan I'm the current Dalli maintainer.  To answer your question, I think the PR looks good.  Just waiting for tests to go green.

**Comment by brandonsturgeon** [comment]
Could we get this message changed?
