### ISSUE TITLE
#exist? shouldn't unserialize

### ISSUE THREAD

**Issue by tpendragon** [petergoldstein/dalli#449]
I have some big objects that take time to unserialize, so I check to see if the key exists with #exists? - turns out that unserializes the object anyways. Any way to bypass that step?

**Comment by petergoldstein** [comment]
So if I'm understanding the discussion correctly, it looks like you're talking about the `get` method on `Dalli::Server` having a hard-coded `true` for the first argument to generic_response.  Instead of a hard-coded response, you'd like to support an option to set that to false, eliminating deserialization.

I think that makes sense, and I'd certainly be willing to review a PR.
