### ISSUE TITLE
Cannot convert ttl ({:expires_in=>30}) to an integer

### ISSUE THREAD

**Issue by hakunin** [petergoldstein/dalli#624]
Version: `2.7.6`
Config:
```
config.cache_store = Dalli::Client.new(
  ENV['MEMCACHEDCLOUD_SERVERS'].split(','), {
    namespace: ENV['HEROKU_APP_NAME'] || Rails.env,
    username: ENV['MEMCACHEDCLOUD_USERNAME'],
    password: ENV['MEMCACHEDCLOUD_PASSWORD']
  }
)
```

Accoring to readme this should work, but doesn't:
```
> Rails.cache.fetch('test', expires_in: 30) { 123 } 
=> Cannot convert ttl ({:expires_in=>30}) to an integer
```

When I pass integer, it works, but isn't that breaking the api setup by Rails?
```
> Rails.cache.fetch('test', 30) { 123 } 
=> 123
```

Looks like the options to specify `expires_in:` was lost here: https://github.com/petergoldstein/dalli/commit/1392e5887ae737e46004bb259a2ad822b2026f47

**Comment by petergoldstein** [comment]
I don't understand this bug report.  The link you reference doesn't seem to have much to do with the problem you're reporting.  Rails.cache is not a Dalli::Client, and the relevant fetch method can be found here - https://github.com/petergoldstein/dalli/blob/master/lib/active_support/cache/dalli_store.rb#L94

Can you please provide a link to a sample app that demonstrates the problem you are reporting?

**Comment by hakunin** [comment]
The stack trace points to the issue being raised client and I've shown that the api has changed in this commit:

https://github.com/petergoldstein/dalli/commit/1392e5887ae737e46004bb259a2ad822b2026f47#diff-529a991515d2e5a278fa5b2cb3e9a83eL87


```
> Rails.cache.fetch('test', expires_in: 30) { 123 } 
Cannot convert ttl ({:expires_in=>30}) to an integer
====================================================
[0] /vendor/bundle/ruby/2.1.0/gems/dalli-2.7.6/lib/dalli/client.rb:278:in `rescue in ttl_or_default'
    273:     end
    274: 
    275:     def ttl_or_default(ttl)
    276:       (ttl || @options[:expires_in]).to_i
    277:     rescue NoMethodError
 => 278:       raise ArgumentError, "Cannot convert ttl (#{ttl}) to an integer"
    279:     end
    280: 
    281:     def groups_for_keys(*keys)
    282:       groups = mapped_keys(keys).flatten.group_by do |key|
    283:         begin
[1] /vendor/bundle/ruby/2.1.0/gems/dalli-2.7.6/lib/dalli/client.rb:276:in `ttl_or_default'
[2] /vendor/bundle/ruby/2.1.0/gems/dalli-2.7.6/lib/dalli/client.rb:94:in `fetch'
```

**Comment by hakunin** [comment]
For anyone in need of a quick fix:
```
module Dalli
  class Client
    def ttl_or_default _ttl
      if _ttl.is_a? Hash
        ttl = _ttl[:expires_in]
      end
      ttl = (ttl || @options[:expires_in]).to_i
    rescue NoMethodError
      raise ArgumentError, "Cannot convert ttl (#{_ttl}) to an integer"
    end
  end
end
```

**Comment by petergoldstein** [comment]
You have demonstrated nothing of the kind, that's my point.  Specifically:

1. The API did not change.  All that happened is that an obscure 'to_i' conversion error was replaced with a specific ArgumentError
2. If this bug report were true, it should mean that many, many, many installations of Dalli are broken.  This is literally the first complaint about this issue we've received.  So this is an extraordinary claim, and hence requires extraordinary evidence.  At a minimum, an app demonstrating this behavior would be nice.
3. Running my system locally shows the expected behavior, and not the error you're reporting.  Specifically, in a Rails console:

```
irb(main):002:0> Rails.cache.fetch('test', expires_in: 30) { 123 }
Cache read: test ({:expires_in=>30})
Dalli::Server#connect 127.0.0.1:11211
127.0.0.1:11211 is back (downtime was 46.482 seconds)
Cache generate: test ({:expires_in=>30})
Cache write: test ({:expires_in=>30})

```
4. I can easily reproduce your error by calling `fetch` on the `Dalli::Client`.  Specifically:

```
irb(main):006:0> Dalli::Client.new.fetch('test', expires_in: 30) { 123 }
Dalli::Server#connect 127.0.0.1:11211
ArgumentError: Cannot convert ttl ({:expires_in=>30}) to an integer
```

So please provide an example app that demonstrates the problem, so we can review it and determine if there's an actual problem, or if there's a configuration error.

**Comment by hakunin** [comment]
Here you go: https://github.com/hakunin/dalli-issue-repro

The Rails.cache points directly to dalli:
```
2.1.5 :003 > Rails.cache
 => #<Dalli::Client:0x007fc48d441a98 ...>
```

Issue can be reproduced:
```
2.1.5 :001 > Rails.cache.fetch('test', expires_in: 30) { 123 } 
Dalli::Server#connect localhost:11211
ArgumentError: Cannot convert ttl ({:expires_in=>30}) to an integer
	from /Users/michal/.rvm/gems/ruby-2.1.5/gems/dalli-2.7.6/lib/dalli/client.rb:278:in `rescue in ttl_or_default'
	from /Users/michal/.rvm/gems/ruby-2.1.5/gems/dalli-2.7.6/lib/dalli/client.rb:276:in `ttl_or_default'
	from /Users/michal/.rvm/gems/ruby-2.1.5/gems/dalli-2.7.6/lib/dalli/client.rb:94:in `fetch'
```

I noticed it installed older dalli version and I had to update it to the latest to be able to reproduce it.

**Comment by hakunin** [comment]
I noticed the config by initialising dalli isn't equivalent to the symbol way.

This works fine:
```
    config.cache_store = [:dalli_store,
      ["localhost"], {
        namespace: "namespace",
      }
    ]
```

**Comment by petergoldstein** [comment]
As I suspected, this is entirely a configuration issue.  You seem to have simply made up how you think a Dalli cache should be configured, rather than following the docs.  Specifically this:

```
 config.cache_store = Dalli::Client.new(
      ["localhost"], {
        namespace: "namespace",
        #username: ENV['MEMCACHEDCLOUD_USERNAME'],
        #password: ENV['MEMCACHEDCLOUD_PASSWORD']
      }
    )
```
is simply incorrect.  The cache_store object is not supposed to be a `Dalli::Client` object, and setting it to one yields exactly the state I described above.

As you note in your follow up comment, if you follow the docs then this problem does not appear.  The Rails.cache class is not a `Dalli::Client` but is a `ActiveSupport::Cache::DalliStore` as expected, and your supposed error doesn't appear.
