### ISSUE TITLE
Errno::ECONNRESET when using get_multi

### ISSUE THREAD

**Issue by PetrKaleta** [petergoldstein/dalli#746]
Please check following sample. Using `dalli (2.7.10)` and `memcached 1.6.0`

```ruby
cache = Dalli::Client.new('localhost:11211')
cache.get_multi(:foo, :bar) # => {}
```
But I also receive this warning `WARN -- : localhost:11211 failed (count: 0) Errno::ECONNRESET: Connection reset by peer`

Why I am getting this warning when using `get_multi`? It happens just in case that there are no values stored under `:foo` and `:bar` keys...

There's no warning when using `cache.get(:foo) # => nil` it happens just with `get_multi`

**Comment by kaptron** [comment]
I am seeing this too, in development on localhost, using `fetch_multi`. However when pointing it to cloud memcached servers (e.g. on Heroku) it works fine. 

For what it's worth, in my own case, using `:mem_cache_store` in `development.rb` still produced a similar error but it at least _worked_ -- meaning hitting `fetch_multi` would produce one error: 
`localhost:11211 failed (count: 0) Errno::ECONNRESET: Connection reset by peer` 

But the call would otherwise function properly, and subsequent calls to `fetch_multi` (with the values now stored in cache) wouldn't complain. However with `:dalli_store` in development, it would actually spit out multiple `Errno::EPIPE: Broken pipe` errors and the values did not seem to be getting cached at all. So my current solution is to just use `:mem_cache_store` in development and just ignore the errors if they do pop up. 

Other notes: I am using Rails 5.2 and Puma 4.3.5. And just to help troubleshoot (since I know there is some description on the readme of Puma + multithreading), I did try using Thin as the server and got the same exact results.

**Comment by mperham** [comment]
It's working fine against master. We're not recommending `:dalli_store` anymore, users should migrate to Rails's official `:mem_cache_store`.

```
irb(main):001:0> require 'dalli'
irb(main):002:0> cache = Dalli::Client.new('localhost:11211')
irb(main):003:0> cache.get_multi(:foo, :bar)
=> {}
irb(main):004:0> cache.set(:foo, :bar)
=> 72057594037927936
irb(main):005:0> cache.get_multi(:foo, :bar)
=> {"foo"=>:bar}
```
